[workspace]
members = [
  "filigree",
  "filigree-cli",
  "sql-migration-sim",
]
exclude = [
  "test-apps/custom_auth_string_ids",
  "test-apps/htmx",
  "test-apps/sveltekit"
]
resolver = "2"

[profile.dev.package.maud_macros]
opt-level = 3
