[package]
name = "filigree-cli"
version = "0.1.0"
edition = "2021"
resolver = "2"

[[bin]]
name = "filigree"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
convert_case = "0.6.0"
error-stack = "0.4.1"
glob = "0.3.1"
ignore = "0.4.21"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tempdir = "0.3.7"
tera = "1.19.1"
thiserror = "1.0.50"
toml = "0.8.8"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
