mod http_error;
mod obfuscate_errors;
mod panic_handler;

pub use http_error::*;
pub use obfuscate_errors::*;
pub use panic_handler::*;
use thiserror::Error;

/// An error to return when failing to parse an order_by field.
/// This is used by the autogenerated code.
#[derive(Debug, Error)]
pub enum OrderByError {
    /// The field is not configured to allow sorting
    #[error("Field is not sortable")]
    InvalidField,
    /// This field restricts the direction in which it can be sorted.
    #[error("Field is not sortable in the requested direction")]
    InvalidDirection,
}

impl HttpError for OrderByError {
    type Detail = ();

    fn status_code(&self) -> hyper::StatusCode {
        hyper::StatusCode::BAD_REQUEST
    }

    fn error_kind(&self) -> &'static str {
        "order_by"
    }

    fn error_detail(&self) -> Self::Detail {
        ()
    }
}
