name = "Post"
id_prefix = "pst"
endpoints = true
allow_id_in_create = true

[[fields]]
name = "subject"
type = "text"
description = "A summary of the post"

[[fields]]
name = "body"
type = "text"
description = "The text of the post"

# A real app would not want to use populate for big arrays such as comments and reactions since we don't want
# to fetch them all every time, but it is convenient for testing.

[[has]]
model = "Comment"
many = true
populate_on_list = "id"
populate_on_get = "id"

[[has]]
model = "Reaction"
many = true
populate_on_get = "data"

[[has]]
model = "Poll"
populate_on_list = "id"
populate_on_get = "data"

# [[has]]
# model = "Tag"
# through = "PostTag"

[[files]]
name = "image"
id_prefix = "pstimg"
bucket = "image_uploads"
many = true
meta.filename = true
meta.size = true
meta.hash = "Blake3"
populate_on_get = "data"
