name = "Report"
id_prefix = "rep"
endpoints = true

[[fields]]
name = "title"
type = "text"


[[fields]]
name = "description"
type = "text"
nullable = true

[[fields]]
name = "ui"
type = "json"
user_access = "read"

[[has]]
model = "ReportSection"
many = true
populate_on_list = "id"
populate_on_get = "data"
update_with_parent = true

# [[has]]
# model = "Tag"
# many = true
# populate_on_list = "id"
# populate_on_get = "data"
# through = "ReportTag"
