name = "ReportSection"
id_prefix = "repsec"
endpoints = true
belongs_to = "Report"

[[fields]]
name = "name"
type = "text"

[[fields]]
name = "viz"
type = "text"

[[fields]]
name = "options"
type = "json"
