use thiserror::Error;
use tokio::signal;

use crate::errors::HttpError;

/// Create a channel which will close when receiving SIGINT or SIGTERM
pub async fn shutdown_signal() -> tokio::sync::oneshot::Receiver<()> {
    let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel();
    tokio::task::spawn(async move {
        let ctrl_c = async {
            signal::ctrl_c().await.expect("failed to listen for ctrl+c");
        };

        #[cfg(unix)]
        let terminate = async {
            signal::unix::signal(signal::unix::SignalKind::terminate())
                .expect("failed to install signal handler")
                .recv()
                .await;
        };

        #[cfg(not(unix))]
        let terminate = std::future::pending::<()>();

        tokio::select! {
            _ = ctrl_c => {},
            _ = terminate => {},
        }

        shutdown_tx.send(()).ok();
    });

    shutdown_rx
}

/// An error to return when failing to parse an order_by field.
/// This is used by the autogenerated code.
#[derive(Debug, Error)]
pub enum OrderByError {
    /// The field is not configured to allow sorting
    #[error("Field is not sortable")]
    InvalidField,
    /// This field restricts the direction in which it can be sorted.
    #[error("Field is not sortable in the requested direction")]
    InvalidDirection,
}

impl HttpError for OrderByError {
    fn status_code(&self) -> hyper::StatusCode {
        hyper::StatusCode::BAD_REQUEST
    }

    fn error_kind(&self) -> &'static str {
        "order_by"
    }
}
