product_name = "Filigree Test App"
company_name = "Daniel Imfeld"

default_auth_scope = "model"

[secrets]
deepgram = "DEEPGRAM_API_KEY"
openai = "OPENAI_API_KEY"

[server]
dotenv = true
hosts = ["localhost"]

[formatter]
rust = ["rustfmt", "+nightly"]
js = ["biome", "format", "--stdin-file-path=stdin.ts" ]
sql = ["pg_format"]

[database]
migrate_on_start = true

[email]
provider = "resend"
from = "support@example.com"

[storage.bucket.pdfs]
bucket = "fl-test-pdfs"
provider = "disk"

[storage.bucket.image_uploads]
bucket = "fl-test-image-uploads"
provider = "disk"

[storage.bucket.image_hosting]
bucket = "fl-test-image-input"
public_url = "https://cdn.example.com"
provider = "cdn"

[storage.provider.disk]
type = "local"
base_path = "/tmp/filigree-test-storage/internal"

[storage.provider.cdn]
preset = "cloudflare_r2"
# define account id below, or via environment: STORAGE_PROVIDER_CDN_ACCOUNT_ID=the-account-id
account_id = "define-in-env"

[job.transcode_video]

[job.send_annoying_emails]

[[job.send_annoying_emails.schedule]]
name = "daily"
schedule = "0 9 * * *"

[[job.send_annoying_emails.schedule]]
name = "monthly"
schedule = "0 0 1 * *"
disabled = true
