product_name = "Filigree Test App"
company_name = "Daniel Imfeld"


dotenv = true
default_auth_scope = "model"

[formatter]
rust = ["rustfmt", "+nightly"]
sql = ["pg_format"]

[database]
migrate_on_start = true

[email]
provider = "none"
from = "support@example.com"
