product_name = "Filigree Test App"
company_name = "Daniel Imfeld"

default_auth_scope = "model"

[server]
dotenv = true
hosts = ["localhost"]

[formatter]
rust = ["rustfmt", "+nightly"]
sql = ["pg_format"]

[database]
migrate_on_start = true

[email]
provider = "resend"
from = "support@example.com"
