[package]
name = "filigree"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
clap = "4.4.11"
convert_case = "0.6.0"
error-stack = "0.4.1"
ignore = "0.4.21"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tempdir = "0.3.7"
thiserror = "1.0.50"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.6.1", features = ["v7"] }

