[package]
name = "filigree-test-app"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.75"
axum = "0.7.2"
chrono = "0.4.31"
filigree = { version = "0.1.0", path = "../filigree" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sqlx = { version = "0.7.3", features = ["postgres"] }
tokio = { version = "1.35.1", features = ["full"] }
tower-sessions = { version = "0.7.0", features = ["postgres-store"] }
